[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/findyourproductionnumber"
  to = "/findyourproductionnumber/index.html"
  status = 200

[[redirects]]
  from = "/service"
  to = "/service/index.html"
  status = 200
